package com.jlg.tutorial.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-11-03T17:08:09.986+01:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://ws.tutorial.jlg.com/", name = "CalculatorWS")
@XmlSeeAlso({ObjectFactory.class})
public interface CalculatorWS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://ws.tutorial.jlg.com/", className = "com.jlg.tutorial.ws.Add")
    @WebMethod
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://ws.tutorial.jlg.com/", className = "com.jlg.tutorial.ws.AddResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
